SELECT 
    ORDER_ID,  
    ORDER_AT_TS,
    RETURNED_DATE,
    COALESCE(IS_REFUNDED, 'not returned') AS IS_REFUNDED,
    SUM(CART_QUANTITY) AS TOTAL_CART_QUANTITY,
    SUM(PRICE_PER_QUANTITY) AS COST_OF_PLANTS,
    ROUND(SUM(AMOUNT_CUSTOMER_PAID), 2) AS TOTAL_AMOUNT_CUSTOMER_PAID,
        ROUND(CASE 
        WHEN IS_REFUNDED = 'yes' THEN 0
        ELSE SUM(AMOUNT_CUSTOMER_PAID)
    END, 2) AS TOTAL_AMOUNT_RECEIVED,
    SHIPPING_COST,  
    TAX_RATE,
    PAYMENT_METHOD, 
    STATE,
FROM {{ ref('int_order_summary') }}
GROUP BY ORDER_ID, SHIPPING_COST, TAX_RATE, ORDER_AT_TS, RETURNED_DATE, IS_REFUNDED, PAYMENT_METHOD, STATE