SELECT
  SESSION_ID, 
  SESSION_AT_TS,
  PAGE_VIEW_NAMES,
  OS, 
  IP, 
  CLIENT_ID,
  ITEM_TYPE_NUM,
  TOTAL_ADDED_TO_CART,
  TOTAL_REMOVED_FROM_CART,
  TOTAL_ITEM,
  DID_ORDER
FROM {{ ref('int_session') }}