SELECT 
    ORDER_ID,
    ORDER_AT_TS,
    RETURNED_DATE,
    COALESCE(IS_REFUNDED, 'not returned') AS IS_REFUNDED,
    TOTAL_CART_QUANTITY,
    COST_OF_PLANTS,
    ROUND(TOTAL_AMOUNT_CUSTOMER_PAID, 2) AS TOTAL_AMOUNT_CUSTOMER_PAID,
    ROUND(CASE 
            WHEN IS_REFUNDED = 'yes' THEN 0
            ELSE TOTAL_AMOUNT_CUSTOMER_PAID
          END, 2) AS TOTAL_AMOUNT_RECEIVED,
    SHIPPING_COST,  
    TAX_RATE,
    PAYMENT_METHOD, 
    STATE
FROM (
    SELECT 
        ORDER_ID,
        ORDER_AT_TS,
        RETURNED_DATE,
        IS_REFUNDED,
        SUM(CART_QUANTITY) OVER (PARTITION BY ORDER_ID) AS TOTAL_CART_QUANTITY,
        SUM(PRICE_PER_QUANTITY) OVER (PARTITION BY ORDER_ID) AS COST_OF_PLANTS,
        SUM(AMOUNT_CUSTOMER_PAID) OVER (PARTITION BY ORDER_ID) AS TOTAL_AMOUNT_CUSTOMER_PAID,
        SHIPPING_COST,  
        TAX_RATE,
        PAYMENT_METHOD, 
        STATE,
        ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY ORDER_AT_TS DESC) AS RN
    FROM {{ ref('int_order_summary') }}
) AS subquery
WHERE RN = 1
ORDER BY ORDER_ID