SELECT _FIVETRAN_ID, 
       PAYMENT_INFO,
       STATE, 
       SESSION_ID, 
       CAST(REPLACE(SHIPPING_COST, 'USD ', '') AS DECIMAL(10, 2)) AS SHIPPING_COST, 
       CLIENT_NAME, 
       PAYMENT_METHOD, 
       TAX_RATE, 
       PHONE, 
       ORDER_ID, 
       _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
       ORDER_AT AS ORDER_AT_TS, 
       SHIPPING_ADDRESS, 
       _FIVETRAN_DELETED
FROM {{ source('snowflake', 'orders') }}